### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yashatkare** [Rjtsahu/Bus-Tracking-Parent#1]
what is id and pass?

**Comment by Rjtsahu** [comment]
This is not a deployed app, you need to host 'School-Bus-Tracking' server and use it.

**Comment by yashatkare** [comment]
How should i run this app

**Comment by angelrethinam** [comment]
Hai plz tel me clearly how should i run this app?

**Comment by Rjtsahu** [comment]
Have a look here https://github.com/Rjtsahu/School-Bus-Tracking/issues/7
