### ISSUE TITLE
log in password

### ISSUE THREAD

**Issue by ghost** [Rjtsahu/Bus-Tracking-Parent#3]
can you pls tell log in id for your app and which database u had used pls elaborate

**Comment by anjarnawai786** [comment]
can you pls tell log in id for your app and which database u had used pls

**Comment by Rjtsahu** [comment]
refer this https://github.com/Rjtsahu/School-Bus-Tracking/issues/7

**Comment by 6ixmediasa** [comment]
i tested on python anywhere .. but when i add drivers or any other user data,, it says cant read database..
