### ISSUE TITLE
Failed to find Build Tools revision 25.0.1

### ISSUE THREAD

**Issue by hrishi1520** [Rjtsahu/Bus-Tracking-Parent#5]
I'm new to Android Studio and found this project interesting as it has GPS module in it. I cloned the project in Studio using git, but I am getting this error " Failed to find Build Tools revision 25.0.1". It would be really grateful if you could help me resolve this issue!

**Comment by Rjtsahu** [comment]
Is ur android studio setup property? is it working with other projects.

Make sure if gradle is working as per the gradle file, else try to update
gradle to Latest version.

Would be helpful if you can provide logs.

**Comment by hrishi1520** [comment]
Sorry but I solved that error, but now the error is that the app is running but then not moving after clicking login button, I guess I'll have to connect it with backend

**Comment by Rjtsahu** [comment]
yes, u need to setup backend server , u can refer my other repo and issues
for same.

**Comment by hrishi1520** [comment]
Please guide me in setting up the backend, I mean which repo to refer?

**Comment by Rjtsahu** [comment]
refer [Server](https://github.com/Rjtsahu/School-Bus-Tracking) , guide [refer](https://github.com/Rjtsahu/School-Bus-Tracking/issues/7l)
